# Generated by Django 5.1.5 on 2026-01-14 02:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("NIT", "NIT"),
                            ("CE", "Cédula de Extranjería"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de documento",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Nombre completo o razón social",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["numero_documento"], name="clientes_numero__b55e8a_idx"
                    ),
                    models.Index(fields=["nombre"], name="clientes_nombre_4aa028_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("COTIZACION", "Cotización"),
                            ("REMISION", "Remisión"),
                            ("FACTURA", "Factura"),
                        ],
                        db_index=True,
                        default="FACTURA",
                        max_length=20,
                        verbose_name="Tipo de comprobante",
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        db_index=True,
                        help_text="FAC-100702, REM-154239, COT-001234",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de comprobante",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "descuento_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento ($)",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total a pagar",
                    ),
                ),
                (
                    "descuento_requiere_aprobacion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere aprobación de gerente"
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("TARJETA", "Tarjeta"),
                            ("CREDITO", "Crédito"),
                        ],
                        default="EFECTIVO",
                        max_length=20,
                        verbose_name="Medio de pago",
                    ),
                ),
                (
                    "efectivo_recibido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Efectivo recibido",
                    ),
                ),
                (
                    "cambio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Cambio",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADA", "Confirmada"),
                            ("ANULADA", "Anulada"),
                        ],
                        db_index=True,
                        default="CONFIRMADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "factura_electronica_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="UUID Factura Electrónica",
                    ),
                ),
                (
                    "factura_electronica_cufe",
                    models.CharField(blank=True, max_length=100, verbose_name="CUFE"),
                ),
                (
                    "fecha_envio_dian",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha envío a DIAN"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="ventas.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "descuento_aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="descuentos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Descuento aprobado por",
                    ),
                ),
                (
                    "remision_origen",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si esta factura se generó desde una remisión",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_generadas",
                        to="ventas.venta",
                        verbose_name="Remisión de origen",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "db_table": "ventas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "descuento_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento por unidad",
                    ),
                ),
                (
                    "iva_porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="IVA (%)"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "afecto_inventario",
                    models.BooleanField(
                        default=True,
                        help_text="False si viene de remisión convertida a factura",
                        verbose_name="Afectó inventario",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Venta",
                "db_table": "detalles_venta",
            },
        ),
        migrations.CreateModel(
            name="AuditoriaDescuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "descuento_solicitado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Descuento solicitado (%)",
                    ),
                ),
                (
                    "descuento_permitido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Descuento permitido (%)",
                    ),
                ),
                (
                    "requirio_aprobacion",
                    models.BooleanField(
                        default=False, verbose_name="Requirió aprobación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aprobaciones_descuento",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="descuentos_aplicados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditorias_descuento",
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Descuento",
                "verbose_name_plural": "Auditorías de Descuentos",
                "db_table": "auditoria_descuentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VentaAnulada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("DEVOLUCION_PARCIAL", "Devolución Parcial"),
                            ("DEVOLUCION_TOTAL", "Devolución Total"),
                            ("ERROR_PRECIOS", "Error con Precios en la Remisión"),
                            ("ERROR_CONCEPTO", "Error por Concepto en la Remisión"),
                            (
                                "COMPRADOR_NO_ACEPTA",
                                "El Comprador no Acepta los Artículos",
                            ),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Motivo de anulación",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "devuelve_inventario",
                    models.BooleanField(
                        default=True,
                        help_text="Si la mercancía regresa al stock",
                        verbose_name="Devuelve al inventario",
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_anuladas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Anulado por",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anulacion",
                        to="ventas.venta",
                        verbose_name="Venta anulada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta Anulada",
                "verbose_name_plural": "Ventas Anuladas",
                "db_table": "ventas_anuladas",
            },
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["numero_comprobante"], name="ventas_numero__bc3aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["tipo_comprobante", "fecha"], name="ventas_tipo_co_566feb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["vendedor", "fecha"], name="ventas_vendedo_df324d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["cliente", "fecha"], name="ventas_cliente_798826_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["estado", "fecha"], name="ventas_estado_1e3fe3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detalleventa",
            index=models.Index(fields=["venta"], name="detalles_ve_venta_i_9d7cc0_idx"),
        ),
        migrations.AddIndex(
            model_name="detalleventa",
            index=models.Index(
                fields=["producto"], name="detalles_ve_product_ed1f1c_idx"
            ),
        ),
    ]
