# Generated by Django 6.0 on 2026-01-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='CC', max_length=50, verbose_name='Tipo de documento'),
        ),
    ]
