# Generated by Django 6.0 on 2026-01-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cliente_numero_documento_and_more'),
        ('ventas', '0002_solicitud_descuento'),
    ]

    operations = [
    ]
