# Generated by Django 6.0 on 2026-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_merge_20260129_2051'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicituddescuento',
            new_name='solicitudes_vendedo_66791c_idx',
            old_name='solicitudes_vendedor_idx',
        ),
        migrations.RenameIndex(
            model_name='solicituddescuento',
            new_name='solicitudes_aprobad_1a810a_idx',
            old_name='solicitudes_aprobador_idx',
        ),
        migrations.RenameIndex(
            model_name='solicituddescuento',
            new_name='solicitudes_estado_193c83_idx',
            old_name='solicitudes_estado_idx',
        ),
        migrations.AddField(
            model_name='solicituddescuento',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='solicituddescuento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
    ]
