# Generated by Django 5.1.5 on 2026-01-31 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ventas",
            "0004_rename_solicitudes_vendedor_idx_solicitudes_vendedo_66791c_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemisionAnulada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("DEVOLUCION_PARCIAL", "Devolución Parcial"),
                            ("DEVOLUCION_TOTAL", "Devolución Total"),
                            ("ERROR_PRECIOS", "Error con Precios en la Remisión"),
                            ("ERROR_CONCEPTO", "Error por Concepto en la Remisión"),
                            (
                                "COMPRADOR_NO_ACEPTA",
                                "El Comprador no Acepta los Artículos",
                            ),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Motivo de anulación",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "devuelve_inventario",
                    models.BooleanField(
                        default=True,
                        help_text="Si la mercancía regresa al stock",
                        verbose_name="Devuelve al inventario",
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remisiones_anuladas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Anulado por",
                    ),
                ),
                (
                    "remision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anulacion_remision",
                        to="ventas.venta",
                        verbose_name="Remisión anulada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remisión Anulada",
                "verbose_name_plural": "Remisiones Anuladas",
                "db_table": "remisiones_anuladas",
            },
        ),
    ]
