# Generated by Django 5.1.5 on 2026-02-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def update_estado_forward(apps, schema_editor):
    Venta = apps.get_model("ventas", "Venta")
    Venta.objects.filter(estado="CONFIRMADA").update(estado="FACTURADA")


def update_estado_backward(apps, schema_editor):
    Venta = apps.get_model("ventas", "Venta")
    Venta.objects.filter(estado="FACTURADA").update(estado="CONFIRMADA")


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_remisionanulada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venta",
            options={
                "ordering": ["-fecha"],
                "permissions": [("caja_facturar", "Puede facturar ventas en caja")],
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.AddField(
            model_name="venta",
            name="creada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creada por",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="enviada_a_caja_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Enviada a caja en"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="enviada_a_caja_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas_enviadas_a_caja",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enviada a caja por",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="facturada_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Facturada en"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="facturada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas_facturadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Facturada por",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("ENVIADA_A_CAJA", "Enviada a caja"),
                    ("FACTURADA", "Facturada"),
                    ("ANULADA", "Anulada"),
                ],
                db_index=True,
                default="BORRADOR",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="numero_comprobante",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="FAC-100702, REM-154239, COT-001234",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Número de comprobante",
            ),
        ),
        migrations.RunPython(update_estado_forward, update_estado_backward),
    ]
