# Generated by Django 6.0 on 2026-02-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_decimal_cantidad'),
        ('ventas', '0006_alter_venta_options_venta_creada_por_and_more'),
    ]

    operations = [
    ]
