# Generated by Claude Code on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulos_permitidos',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Configuración de acceso a módulos y secciones del sistema',
                null=True,
                verbose_name='Módulos permitidos'
            ),
        ),
    ]
