# Generated by Django 5.1.5 on 2026-02-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_modulos_permitidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="es_cajero",
            field=models.BooleanField(default=False, verbose_name="Es cajero"),
        ),
    ]
