# Generated by Django 6.0 on 2026-01-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracion_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='plantilla_factura_carta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='plantilla_factura_tirilla',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='plantilla_nota_credito_carta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='plantilla_nota_credito_tirilla',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='plantilla_remision_carta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='plantilla_remision_tirilla',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracionmodulos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
