# Generated by Django 5.1.5 on 2026-01-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_configuracionfacturacion_plantilla_factura_carta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impuesto",
            name="es_exento",
        ),
        migrations.RemoveField(
            model_name="impuesto",
            name="porcentaje",
        ),
        migrations.RemoveField(
            model_name="impuesto",
            name="valor",
        ),
    ]
