# Generated by Django 5.1.5 on 2026-01-24 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_configuracionfacturacion_plantilla_factura_carta_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditoriaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(db_index=True)),
                ("usuario_nombre", models.CharField(max_length=150)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREAR", "Crear"),
                            ("ACTUALIZAR", "Actualizar"),
                            ("ELIMINAR", "Eliminar"),
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("OTRO", "Otro"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("modelo", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "objeto_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("notas", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "archivado_en",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría Archivado",
                "verbose_name_plural": "Registros de Auditoría Archivados",
                "db_table": "auditoria_archivo",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("CREAR", "Crear"),
                    ("ACTUALIZAR", "Actualizar"),
                    ("ELIMINAR", "Eliminar"),
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("OTRO", "Otro"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="fecha_hora",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="modelo",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="objeto_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(fields=["-fecha_hora"], name="auditoria_fh_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["usuario", "-fecha_hora"], name="auditoria_user_fh_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["accion", "-fecha_hora"], name="auditoria_act_fh_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditoriaarchivo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditorias_archivo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriaarchivo",
            index=models.Index(fields=["-fecha_hora"], name="aud_arch_fh_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoriaarchivo",
            index=models.Index(
                fields=["usuario", "-fecha_hora"], name="aud_arch_user_fh_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriaarchivo",
            index=models.Index(
                fields=["accion", "-fecha_hora"], name="aud_arch_act_fh_idx"
            ),
        ),
    ]
