# Generated by Django 6.0 on 2026-01-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditoriaarchivo_alter_auditoria_accion_and_more'),
        ('core', '0008_simplify_impuesto_model'),
    ]

    operations = [
    ]