# Generated by Django 6.0 on 2026-03-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fix_producto_iva_tribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['nombre', 'id'], 'verbose_name': 'Impuesto', 'verbose_name_plural': 'Impuestos'},
        ),
    ]
