# Generated by Django 6.0 on 2026-03-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_impuesto_options'),
        ('core', '0012_configuracionfacturacion_redondeo_caja'),
    ]

    operations = [
    ]
