# Generated by Django 5.1.5 on 2026-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_drop_intercambio_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="ambiente_factus",
            field=models.CharField(default="SANDBOX", max_length=20),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_numbering_range_id_factura_venta",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_numbering_range_id_nota_credito",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="modo_operacion_electronica",
            field=models.CharField(
                choices=[("FACTUS_MANAGED", "Numeración oficial gestionada en Factus")],
                default="FACTUS_MANAGED",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="permitir_cache_metadatos_factus",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="prefijo_factura_electronica",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
