# Generated by Django 5.1.5 on 2026-04-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_configuracionfacturacion_ambiente_factus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="numero_cotizacion",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="prefijo_cotizacion",
            field=models.CharField(default="COT", max_length=10),
        ),
    ]
