# Generated by Django 5.1.5 on 2026-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_configuracionfacturacion_numero_cotizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_current",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_document_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_environment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_range_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_range_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_range_prefix",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_range_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_resolution_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_valid_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
