# Generated by Django 5.1.5 on 2026-04-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_configuracionfacturacion_factus_factura_venta_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_current",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_document_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_environment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_range_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_range_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_range_prefix",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_range_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_resolution_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_current",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_document_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_environment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_range_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_range_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_range_prefix",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_range_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_resolution_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_current",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_document_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_environment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_range_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_range_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_range_prefix",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_range_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_resolution_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_current",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_document_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_environment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_range_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_range_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_range_prefix",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_range_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_resolution_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_numbering_range_id_documento_soporte",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_numbering_range_id_nota_ajuste_documento_soporte",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracionfacturacion",
            name="factus_numbering_range_id_nota_debito",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
