# Generated by Django 5.1.5 on 2026-04-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0018_configuracionfacturacion_factus_documento_soporte_current_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_document_code",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_documento_soporte_range_prefix",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_document_code",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_factura_venta_range_prefix",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_document_code",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_nota_ajuste_documento_soporte_range_prefix",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_document_code",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_nota_credito_range_prefix",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_document_code",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="configuracionfacturacion",
            name="factus_nota_debito_range_prefix",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
