# Generated by Django 5.1.5 on 2026-01-14 00:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mecanico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Mecánico",
                "verbose_name_plural": "Mecánicos",
                "db_table": "mecanicos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["nombre"], name="mecanicos_nombre_3b7ae2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Moto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("anio", models.IntegerField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motos",
                        to="ventas.cliente",
                    ),
                ),
                (
                    "mecanico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motos",
                        to="taller.mecanico",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motos",
                        to="inventario.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moto",
                "verbose_name_plural": "Motos",
                "db_table": "motos",
                "ordering": ["placa"],
            },
        ),
        migrations.CreateModel(
            name="OrdenTaller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_PROCESO", "En proceso"),
                            ("LISTO_FACTURAR", "Listo para facturar"),
                            ("FACTURADO", "Facturado"),
                        ],
                        default="EN_PROCESO",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "mecanico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="taller.mecanico",
                    ),
                ),
                (
                    "moto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="taller.moto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_taller",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de taller",
                "verbose_name_plural": "Órdenes de taller",
                "db_table": "ordenes_taller",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrdenRepuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repuestos_taller",
                        to="inventario.producto",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repuestos",
                        to="taller.ordentaller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repuesto de orden",
                "verbose_name_plural": "Repuestos de orden",
                "db_table": "ordenes_repuestos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="moto",
            index=models.Index(fields=["placa"], name="motos_placa_3922d6_idx"),
        ),
        migrations.AddIndex(
            model_name="moto",
            index=models.Index(fields=["marca"], name="motos_marca_e1f377_idx"),
        ),
        migrations.AddIndex(
            model_name="ordentaller",
            index=models.Index(fields=["estado"], name="ordenes_tal_estado_177f6a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ordenrepuesto",
            unique_together={("orden", "producto")},
        ),
    ]
