# Generated by Django 5.0.1 on 2026-03-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0008_venta_inventario_ya_afectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cufe', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='CUFE')),
                ('uuid', models.CharField(db_index=True, max_length=128, verbose_name='UUID')),
                ('number', models.CharField(db_index=True, max_length=64, verbose_name='Número de factura')),
                ('xml_url', models.URLField(max_length=500, verbose_name='URL XML')),
                ('pdf_url', models.URLField(max_length=500, verbose_name='URL PDF')),
                ('qr', models.TextField(verbose_name='Código QR')),
                ('status', models.CharField(db_index=True, max_length=64, verbose_name='Estado Factus/DIAN')),
                ('response_json', models.JSONField(verbose_name='Respuesta completa de Factus')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_electronica_factus', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'db_table': 'facturacion_facturas_electronicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['status', '-created_at'], name='facturacion_status_835148_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['number', '-created_at'], name='facturacion_number_bf1363_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['uuid'], name='facturacion_uuid_2cdbfa_idx'),
        ),
    ]
