# Generated by Django 5.1.5 on 2026-03-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_facturaelectronica_dian_qr_pos_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaCreditoElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("uuid", models.CharField(blank=True, max_length=100, null=True)),
                ("cufe", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACEPTADA", "Aceptada DIAN"),
                            ("RECHAZADA", "Rechazada DIAN"),
                            ("ERROR", "Error de envío"),
                            ("EN_PROCESO", "En proceso"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("xml_url", models.URLField(blank=True, null=True)),
                ("pdf_url", models.URLField(blank=True, null=True)),
                ("response_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_credito",
                        to="facturacion.facturaelectronica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Crédito Electrónica",
                "verbose_name_plural": "Notas Crédito Electrónicas",
                "db_table": "facturacion_notas_credito_electronicas",
                "ordering": ["-created_at"],
            },
        ),
    ]
