# Generated by Django 5.1.5 on 2026-03-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_notacreditoelectronica"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoSoporteElectronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("proveedor_nombre", models.CharField(max_length=200)),
                ("proveedor_documento", models.CharField(max_length=50)),
                ("proveedor_tipo_documento", models.CharField(max_length=20)),
                ("cufe", models.CharField(blank=True, max_length=150, null=True)),
                ("uuid", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACEPTADA", "Aceptada DIAN"),
                            ("RECHAZADA", "Rechazada DIAN"),
                            ("ERROR", "Error de envío"),
                            ("EN_PROCESO", "En proceso"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("xml_url", models.URLField(blank=True, null=True)),
                ("pdf_url", models.URLField(blank=True, null=True)),
                ("response_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Documento Soporte Electrónico",
                "verbose_name_plural": "Documentos Soporte Electrónicos",
                "db_table": "facturacion_documentos_soporte_electronicos",
                "ordering": ["-created_at"],
            },
        ),
    ]
