# Generated by Django 5.1.5 on 2026-03-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0007_notaajustedocumentosoporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="RangoNumeracionDIAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefijo", models.CharField(max_length=20)),
                ("desde", models.IntegerField()),
                ("hasta", models.IntegerField()),
                ("resolucion", models.CharField(max_length=100)),
                ("consecutivo_actual", models.IntegerField()),
                ("fecha_autorizacion", models.DateField(null=True)),
                ("fecha_expiracion", models.DateField(null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rango de Numeración DIAN",
                "verbose_name_plural": "Rangos de Numeración DIAN",
                "db_table": "facturacion_rangos_numeracion_dian",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionDIAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nit_empresa", models.CharField(max_length=20)),
                ("software_id", models.CharField(max_length=200)),
                ("software_pin", models.CharField(max_length=200)),
                ("prefijo_facturacion", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rango_facturacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facturacion.rangonumeraciondian",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración DIAN",
                "verbose_name_plural": "Configuración DIAN",
                "db_table": "facturacion_configuracion_dian",
            },
        ),
    ]
