# Generated by Django 6.0 on 2026-03-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_rangonumeraciondian_selection_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rangonumeraciondian',
            new_name='facturacion_environ_cd9daf_idx',
            old_name='facturacion__environ_cf6ae4_idx',
        ),
        migrations.RenameIndex(
            model_name='rangonumeraciondian',
            new_name='facturacion_environ_3e701b_idx',
            old_name='facturacion__environ_cf4f41_idx',
        ),
    ]
