# Generated by Django 5.1.5 on 2026-04-02 16:49

from django.db import migrations, models


def backfill_electronic_state(apps, schema_editor):
    FacturaElectronica = apps.get_model("facturacion", "FacturaElectronica")
    mapping = {
        "ERROR": "ERROR_INTEGRACION",
        "EN_PROCESO": "PENDIENTE_REINTENTO",
        "ACEPTADA": "ACEPTADA",
        "RECHAZADA": "RECHAZADA",
    }
    for factura in FacturaElectronica.objects.all().only("id", "status", "codigo_error", "number", "cufe"):
        estado = mapping.get(factura.status, factura.status or "PENDIENTE_REINTENTO")
        if estado == "ACEPTADA" and factura.codigo_error == "OBSERVACIONES_FACTUS":
            estado = "ACEPTADA_CON_OBSERVACIONES"
        factura.estado_electronico = estado
        factura.status = estado
        factura.emitida_en_factus = bool(factura.number and factura.cufe)
        factura.save(update_fields=["estado_electronico", "status", "emitida_en_factus"])


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0012_facturaelectronica_flujo_completo_fields"),
        ("ventas", "0010_alter_venta_efectivo_recibido_alter_venta_cambio"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaelectronica",
            name="emitida_en_factus",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Emitida en Factus"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="estado_electronico",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                default="PENDIENTE_REINTENTO",
                max_length=40,
                verbose_name="Estado electrónico Factus",
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="estado_factus_raw",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Estado crudo Factus",
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="last_retry_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último reintento"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="next_retry_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Próximo reintento"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="observaciones_json",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Observaciones Factus normalizadas",
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad de reintentos"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="ultima_sincronizacion_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última sincronización"
            ),
        ),
        migrations.AlterField(
            model_name="documentosoporteelectronico",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="facturaelectronica",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                default="PENDIENTE_REINTENTO",
                max_length=40,
                verbose_name="Estado electrónico (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="notaajustedocumentosoporte",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="facturaelectronica",
            index=models.Index(
                fields=["estado_electronico", "-created_at"],
                name="facturacion_estado__ab79c4_idx",
            ),
        ),
        migrations.RunPython(backfill_electronic_state, migrations.RunPython.noop),
    ]
