# Generated by Django 5.1.5 on 2026-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0013_facturaelectronica_emitida_en_factus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturaelectronica",
            name="pdf_local_path",
            field=models.TextField(
                blank=True, default="", verbose_name="Ruta local PDF"
            ),
        ),
        migrations.AlterField(
            model_name="facturaelectronica",
            name="pdf_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="URL PDF"
            ),
        ),
        migrations.AlterField(
            model_name="facturaelectronica",
            name="public_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="URL pública"
            ),
        ),
        migrations.AlterField(
            model_name="facturaelectronica",
            name="qr_image_url",
            field=models.URLField(
                blank=True,
                max_length=2048,
                null=True,
                verbose_name="URL imagen QR remota",
            ),
        ),
        migrations.AlterField(
            model_name="facturaelectronica",
            name="xml_local_path",
            field=models.TextField(
                blank=True, default="", verbose_name="Ruta local XML"
            ),
        ),
        migrations.AlterField(
            model_name="facturaelectronica",
            name="xml_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="URL XML"
            ),
        ),
    ]
