# Generated by Django 5.1.5 on 2026-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0014_alter_facturaelectronica_pdf_local_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaelectronica",
            name="qr_image_data",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido QR embebido/base64"
            ),
        ),
    ]
