# Generated by Django 5.1.5 on 2026-04-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0015_facturaelectronica_qr_image_data"),
        ("inventario", "0008_producto_ultima_compra"),
        ("ventas", "0010_alter_venta_efectivo_recibido_alter_venta_cambio"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaelectronica",
            name="estado_acreditacion",
            field=models.CharField(
                choices=[
                    ("ACTIVA", "Activa"),
                    ("CREDITADA_PARCIAL", "Creditada parcial"),
                    ("CREDITADA_TOTAL", "Creditada total"),
                ],
                db_index=True,
                default="ACTIVA",
                max_length=30,
                verbose_name="Estado comercial de acreditación",
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="codigo_error",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="concepto",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="consecutivo",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="correo_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="correo_enviado_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="email_content_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="estado_electronico",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                default="PENDIENTE_REINTENTO",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="estado_local",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("ENVIADA_A_FACTUS", "Enviada a Factus"),
                    ("ACEPTADA", "Aceptada"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("ELIMINADA_LOCAL", "Eliminada local"),
                    ("ELIMINADA_EN_FACTUS", "Eliminada en Factus"),
                ],
                db_index=True,
                default="BORRADOR",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="mensaje_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="motivo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="pdf_local_path",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="prefijo",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="public_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="qr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="qr_image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="reference_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="request_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="status_raw_factus",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="tipo_nota",
            field=models.CharField(
                choices=[("PARCIAL", "Parcial"), ("TOTAL", "Total")],
                db_index=True,
                default="PARCIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="venta_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_credito_electronicas",
                to="ventas.venta",
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="xml_local_path",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="number",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACEPTADA", "Aceptada"),
                    ("ACEPTADA_CON_OBSERVACIONES", "Aceptada con observaciones"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("PENDIENTE_REINTENTO", "Pendiente de reintento"),
                ],
                db_index=True,
                default="PENDIENTE_REINTENTO",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="NotaCreditoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_original_facturada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cantidad_ya_acreditada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cantidad_a_acreditar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "base_impuesto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuesto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("afecta_inventario", models.BooleanField(default=False)),
                (
                    "motivo_linea",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detalle_venta_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_credito_detalle",
                        to="ventas.detalleventa",
                    ),
                ),
                (
                    "nota_credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="facturacion.notacreditoelectronica",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de nota crédito",
                "verbose_name_plural": "Detalles de nota crédito",
                "db_table": "facturacion_notas_credito_detalle",
                "indexes": [
                    models.Index(
                        fields=["detalle_venta_original"],
                        name="facturacion_detalle_275a4f_idx",
                    ),
                    models.Index(
                        fields=["producto"], name="facturacion_product_8639df_idx"
                    ),
                ],
            },
        ),
    ]
