# Generated by Django 5.1.5 on 2026-04-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0016_facturaelectronica_estado_acreditacion_and_more"),
        ("ventas", "0010_alter_venta_efectivo_recibido_alter_venta_cambio"),
    ]

    operations = [
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="email_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="remote_status_raw",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="synchronized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="estado_local",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("PENDIENTE_ENVIO", "Pendiente de envío"),
                    ("EN_PROCESO", "En proceso DIAN"),
                    ("ACEPTADA", "Aceptada"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ERROR_PERSISTENCIA", "Error de persistencia"),
                    ("ANULADA_LOCAL", "Anulada local"),
                    ("ELIMINADA_EN_FACTUS", "Eliminada en Factus"),
                ],
                db_index=True,
                default="BORRADOR",
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="notacreditoelectronica",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "estado_local__in",
                        ["BORRADOR", "PENDIENTE_ENVIO", "EN_PROCESO", "ACEPTADA"],
                    )
                ),
                fields=("factura", "tipo_nota"),
                name="uq_nota_credito_abierta_factura_tipo",
            ),
        ),
    ]
