# Generated by Django 5.1.5 on 2026-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0018_notacreditoelectronica_conflicto_factus_state"),
        ("ventas", "0010_alter_venta_efectivo_recibido_alter_venta_cambio"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notacreditoelectronica",
            name="uq_nota_credito_abierta_factura_tipo",
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="cufe",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="estado_local",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("PENDIENTE_ENVIO", "Pendiente de envío"),
                    ("PENDIENTE_DIAN", "Pendiente DIAN"),
                    ("CONFLICTO_FACTUS", "Conflicto Factus (sin confirmación remota)"),
                    ("ACEPTADA", "Aceptada"),
                    ("RECHAZADA", "Rechazada"),
                    ("ERROR_INTEGRACION", "Error de integración"),
                    ("ANULADA_LOCAL", "Anulada local"),
                ],
                db_index=True,
                default="BORRADOR",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="number",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="notacreditoelectronica",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "estado_local__in",
                        [
                            "BORRADOR",
                            "PENDIENTE_ENVIO",
                            "PENDIENTE_DIAN",
                            "CONFLICTO_FACTUS",
                        ],
                    )
                ),
                fields=("factura", "tipo_nota"),
                name="uq_nota_credito_abierta_factura_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="notacreditoelectronica",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "estado_local__in",
                        [
                            "BORRADOR",
                            "PENDIENTE_ENVIO",
                            "PENDIENTE_DIAN",
                            "CONFLICTO_FACTUS",
                            "ACEPTADA",
                        ],
                    ),
                    ("tipo_nota", "TOTAL"),
                ),
                fields=("factura",),
                name="uq_nota_credito_total_activa_factura",
            ),
        ),
        migrations.AddConstraint(
            model_name="notacreditoelectronica",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="uq_nota_credito_number_non_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="notacreditoelectronica",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cufe__isnull", False), models.Q(("cufe", ""), _negated=True)
                ),
                fields=("cufe",),
                name="uq_nota_credito_cufe_non_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="notacreditoelectronica",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_code", ""), _negated=True),
                fields=("reference_code",),
                name="uq_nota_credito_reference_code_non_empty",
            ),
        ),
    ]
