# Generated by Django 5.1.5 on 2026-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion",
            "0019_remove_notacreditoelectronica_uq_nota_credito_abierta_factura_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="last_remote_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="remote_identifier",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="notacreditoelectronica",
            name="sync_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notacreditoelectronica",
            name="reference_code",
            field=models.CharField(db_index=True, default="", max_length=120),
        ),
    ]
