# Generated by Django 5.1.5 on 2026-04-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0020_notacreditoelectronica_last_remote_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rangonumeraciondian",
            name="document_code",
            field=models.CharField(
                choices=[
                    ("FACTURA_VENTA", "Factura de venta"),
                    ("NOTA_CREDITO", "Nota crédito"),
                ],
                db_index=True,
                default="FACTURA_VENTA",
                max_length=30,
                verbose_name="Tipo de documento",
            ),
        ),
    ]
