# Generated by Django 5.1.5 on 2026-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0021_alter_rangonumeraciondian_document_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rangonumeraciondian",
            name="document_code",
            field=models.CharField(
                choices=[
                    ("FACTURA_VENTA", "Factura de venta"),
                    ("NOTA_CREDITO", "Nota crédito"),
                    ("DOCUMENTO_SOPORTE", "Documento soporte"),
                    (
                        "NOTA_AJUSTE_DOCUMENTO_SOPORTE",
                        "Nota de ajuste documento soporte",
                    ),
                    ("NOTA_DEBITO", "Nota débito"),
                    ("REMISION", "Remisión (consecutivo local)"),
                ],
                db_index=True,
                default="FACTURA_VENTA",
                max_length=30,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AddConstraint(
            model_name="rangonumeraciondian",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_selected_local", True)),
                fields=("environment", "document_code"),
                name="uq_rango_selected_env_doc",
            ),
        ),
    ]
