# Generated by Django 5.1.5 on 2026-04-05 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0022_alter_rangonumeraciondian_document_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="document_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="factus_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="ID original en Factus",
            ),
        ),
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="is_associated_to_software",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Asociado al software en Factus",
            ),
        ),
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="is_expired_remote",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Vencido remoto en Factus"
            ),
        ),
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rangonumeraciondian",
            name="technical_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="RemisionNumeracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=20, unique=True)),
                ("current", models.PositiveIntegerField(default=1)),
                ("range_from", models.PositiveIntegerField(default=1)),
                ("range_to", models.PositiveIntegerField(default=99999999)),
                (
                    "resolution_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remisiones_numeracion_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Numeración de remisiones",
                "verbose_name_plural": "Numeraciones de remisiones",
                "db_table": "facturacion_remisiones_numeracion",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RemisionNumeracionHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_data", models.JSONField(blank=True, default=dict)),
                ("new_data", models.JSONField(blank=True, default=dict)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remisiones_numeracion_historial",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "numeracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="facturacion.remisionnumeracion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial numeración remisiones",
                "verbose_name_plural": "Historiales numeración remisiones",
                "db_table": "facturacion_remisiones_numeracion_historial",
                "ordering": ["-changed_at"],
            },
        ),
    ]
