# Generated by Django 5.1.5 on 2026-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0023_rangonumeraciondian_document_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaelectronica",
            name="email_last_error",
            field=models.TextField(
                blank=True, default="", verbose_name="Último error de correo Factus"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de envío remoto Factus"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="email_subject",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Asunto del correo Factus",
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="email_zip_local_path",
            field=models.TextField(
                blank=True, default="", verbose_name="Ruta local ZIP del correo"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="last_assets_sync_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última sincronización de activos"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="send_email_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Enviar correo automático en Factus"
            ),
        ),
    ]
