# Generated by Django 5.1.5 on 2026-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0025_unify_facturaelectronica_estado_canonico"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactusNumberingRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.CharField(max_length=50)),
                ("prefix", models.CharField(max_length=20)),
                ("resolution_number", models.CharField(max_length=50)),
                ("from_number", models.BigIntegerField()),
                ("to_number", models.BigIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "technical_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Factus Numbering Range",
                "verbose_name_plural": "Factus Numbering Ranges",
                "db_table": "facturacion_factus_numbering_ranges",
                "indexes": [
                    models.Index(
                        fields=["document", "is_active", "end_date"],
                        name="facturacion_documen_e12c9a_idx",
                    )
                ],
                "unique_together": {("prefix", "resolution_number")},
            },
        ),
    ]
