# Generated by Django 5.1.5 on 2026-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0026_factusnumberingrange"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_authorized_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_authorized_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_consecutive_number",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Consecutivo oficial Factus"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_number_prefix",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Prefijo oficial Factus",
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_numbering_range_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID rango Factus"
            ),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_numbering_range_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_resolution_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_resolution_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_resolution_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facturaelectronica",
            name="factus_resolution_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
