# Generated by Django 5.1.5 on 2026-01-14 02:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Para ordenar las categorías en el sistema",
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categorias",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(fields=["nombre"], name="categorias_nombre_bb19a2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "nit",
                    models.CharField(blank=True, max_length=20, verbose_name="NIT"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Persona de contacto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "proveedores",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="proveedores_nombre_4e7949_idx"
                    ),
                    models.Index(fields=["nit"], name="proveedores_nit_dea009_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código de barras o SKU",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        verbose_name="Nombre del producto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "precio_costo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio de costo",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio de venta",
                    ),
                ),
                (
                    "precio_venta_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio mínimo permitido (con descuento máximo)",
                        max_digits=12,
                        verbose_name="Precio de venta mínimo",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="Stock actual"
                    ),
                ),
                (
                    "stock_minimo",
                    models.IntegerField(
                        default=5,
                        help_text="Alerta cuando el stock llegue a este nivel",
                        verbose_name="Stock mínimo",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        default="UND",
                        help_text="UND, PAR, KG, LT, etc.",
                        max_length=20,
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "iva_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=19,
                        max_digits=5,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "aplica_descuento",
                    models.BooleanField(default=True, verbose_name="Aplica descuento"),
                ),
                (
                    "es_servicio",
                    models.BooleanField(
                        default=False,
                        help_text="Marca si es un servicio en lugar de producto físico",
                        verbose_name="Es servicio",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="inventario.categoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="inventario.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (Compra)"),
                            ("SALIDA", "Salida (Venta)"),
                            ("AJUSTE", "Ajuste Manual"),
                            ("DEVOLUCION", "Devolución"),
                            ("BAJA", "Dar de Baja"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        help_text="Positivo para entradas, negativo para salidas",
                        verbose_name="Cantidad",
                    ),
                ),
                ("stock_anterior", models.IntegerField(verbose_name="Stock anterior")),
                ("stock_nuevo", models.IntegerField(verbose_name="Stock nuevo")),
                (
                    "costo_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Costo unitario"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="No. Factura, Remisión, etc.",
                        max_length=100,
                        verbose_name="Referencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventario.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "db_table": "movimientos_inventario",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["producto", "created_at"],
                        name="movimientos_product_70c5a9_idx",
                    ),
                    models.Index(
                        fields=["tipo", "created_at"],
                        name="movimientos_tipo_aeac52_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["codigo"], name="productos_codigo_1fb639_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["nombre"], name="productos_nombre_d31432_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["categoria", "is_active"], name="productos_categor_45e256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["stock"], name="productos_stock_2e1108_idx"),
        ),
    ]
