# Generated by Django 5.1.5 on 2026-02-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_add_iva_exento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoFavorito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "alias",
                    models.CharField(blank=True, max_length=120, verbose_name="Alias"),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Orden sugerido para mostrar en la lista",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to="inventario.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_favoritos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto favorito",
                "verbose_name_plural": "Productos favoritos",
                "db_table": "productos_favoritos",
                "ordering": ["orden", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="productos_f_usuario_2f191d_idx"
                    ),
                    models.Index(
                        fields=["producto"], name="productos_f_product_f08140_idx"
                    ),
                ],
                "unique_together": {("usuario", "producto")},
            },
        ),
    ]
