# Generated by Django 6.0 on 2026-02-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_decimal_stock_cantidad'),
        ('inventario', '0004_productofavorito'),
    ]

    operations = [
    ]
