# Generated by Django 6.0 on 2026-02-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_merge_20260202_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('LT', 'Litro'), ('MT', 'Metro')], default='KG', help_text='KG, LT, MT', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
