# Generated by Django 6.0 on 2026-02-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_unidad_medida_na_default'),
        ('inventario', '0006_alter_producto_unidad_medida'),
    ]

    operations = [
    ]
