# Generated by Django 5.1.5 on 2026-03-05 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventas", "0008_venta_inventario_ya_afectado"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoSoporteElectronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("tercero_identificacion", models.CharField(max_length=50)),
                ("estado", models.CharField(default="PENDIENTE", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("respuesta_api", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Documento Soporte Electrónico",
                "verbose_name_plural": "Documentos Soporte Electrónicos",
                "db_table": "documentos_soporte_electronicos",
            },
        ),
        migrations.CreateModel(
            name="FactusToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(verbose_name="Access token")),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer", max_length=40, verbose_name="Token type"
                    ),
                ),
                (
                    "expires_in",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duración en segundos"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="Expira en"),
                ),
                (
                    "scope",
                    models.CharField(blank=True, max_length=255, verbose_name="Scope"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Token Factus",
                "verbose_name_plural": "Tokens Factus",
                "db_table": "factus_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomologacionMedioPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("payment_method_code", models.CharField(db_index=True, max_length=20)),
                ("nombre", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "Homologación Medio de Pago",
                "verbose_name_plural": "Homologaciones Medio de Pago",
                "db_table": "fe_homologacion_medio_pago",
            },
        ),
        migrations.CreateModel(
            name="HomologacionMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("municipality_id", models.PositiveIntegerField(db_index=True)),
                ("nombre", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "Homologación Municipio",
                "verbose_name_plural": "Homologaciones Municipio",
                "db_table": "fe_homologacion_municipio",
            },
        ),
        migrations.CreateModel(
            name="HomologacionTributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("tribute_id", models.PositiveIntegerField(db_index=True)),
                ("nombre", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "Homologación Tributo",
                "verbose_name_plural": "Homologaciones Tributo",
                "db_table": "fe_homologacion_tributo",
            },
        ),
        migrations.CreateModel(
            name="HomologacionUnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("unit_measure_id", models.PositiveIntegerField(db_index=True)),
                ("nombre", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "Homologación Unidad de Medida",
                "verbose_name_plural": "Homologaciones Unidad de Medida",
                "db_table": "fe_homologacion_unidad_medida",
            },
        ),
        migrations.CreateModel(
            name="FacturaElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Reference code",
                    ),
                ),
                (
                    "numbering_range_id",
                    models.PositiveIntegerField(
                        verbose_name="Rango de numeración Factus"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIANDO", "Enviando"),
                            ("ACEPTADA_DIAN", "Aceptada por DIAN"),
                            ("RECHAZADA_DIAN", "Rechazada por DIAN"),
                            ("ERROR_API", "Error API"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Payload enviado"
                    ),
                ),
                (
                    "respuesta_api",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta Factus"
                    ),
                ),
                (
                    "uuid_factus",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="UUID Factus",
                    ),
                ),
                (
                    "cufe",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="CUFE"
                    ),
                ),
                (
                    "intentos_envio",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos de envío"
                    ),
                ),
                (
                    "ultimo_intento_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último intento"
                    ),
                ),
                (
                    "enviada_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviada a Factus"
                    ),
                ),
                (
                    "aceptada_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aceptada por DIAN"
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factura_electronica",
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura Electrónica",
                "verbose_name_plural": "Facturas Electrónicas",
                "db_table": "facturas_electronicas",
            },
        ),
        migrations.CreateModel(
            name="NotaCreditoElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("estado", models.CharField(default="PENDIENTE", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("respuesta_api", models.JSONField(blank=True, default=dict)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_credito",
                        to="facturacion_electronica.facturaelectronica",
                        verbose_name="Factura electrónica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Crédito Electrónica",
                "verbose_name_plural": "Notas Crédito Electrónicas",
                "db_table": "notas_credito_electronicas",
            },
        ),
        migrations.AddIndex(
            model_name="facturaelectronica",
            index=models.Index(
                fields=["estado", "created_at"], name="facturas_el_estado_1579dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facturaelectronica",
            index=models.Index(
                fields=["ultimo_intento_at"], name="facturas_el_ultimo__7eed42_idx"
            ),
        ),
    ]
