# Generated by Django 5.1.5 on 2026-03-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentificacionFactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('factus_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Documento de Identificación Factus',
                'verbose_name_plural': 'Documentos de Identificación Factus',
                'db_table': 'fe_catalogo_documento_identificacion',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['factus_id'], name='fe_catalogo__factus__36197f_idx'),
                    models.Index(fields=['codigo'], name='fe_catalogo__codigo_d4afaf_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MetodoPagoFactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('factus_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Método de Pago Factus',
                'verbose_name_plural': 'Métodos de Pago Factus',
                'db_table': 'fe_catalogo_metodo_pago',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['factus_id'], name='fe_catalogo__factus__11ac12_idx'),
                    models.Index(fields=['codigo'], name='fe_catalogo__codigo_7db5b4_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MunicipioFactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('factus_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Municipio Factus',
                'verbose_name_plural': 'Municipios Factus',
                'db_table': 'fe_catalogo_municipio',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['factus_id'], name='fe_catalogo__factus__ad799e_idx'),
                    models.Index(fields=['codigo'], name='fe_catalogo__codigo_72da58_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='TributoFactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('factus_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tributo Factus',
                'verbose_name_plural': 'Tributos Factus',
                'db_table': 'fe_catalogo_tributo',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['factus_id'], name='fe_catalogo__factus__f668f6_idx'),
                    models.Index(fields=['codigo'], name='fe_catalogo__codigo_4048d2_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedidaFactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('factus_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Unidad de Medida Factus',
                'verbose_name_plural': 'Unidades de Medida Factus',
                'db_table': 'fe_catalogo_unidad_medida',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['factus_id'], name='fe_catalogo__factus__fbd886_idx'),
                    models.Index(fields=['codigo'], name='fe_catalogo__codigo_2bc059_idx'),
                ],
            },
        ),
    ]
