# Generated by Django 5.1.5 on 2026-03-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_notacreditoelectronica'),
        ('facturacion_electronica', '0003_unify_factura_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditoelectronica',
            name='factura',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='notas_credito_legacy',
                to='facturacion.facturaelectronica',
                verbose_name='Factura electrónica',
            ),
        ),
    ]
