# Generated by Django 6.0 on 2026-03-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0005_factustoken_refresh_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoidentificacionfactus',
            options={'verbose_name': 'Documento de Identificación Factus', 'verbose_name_plural': 'Documentos de Identificación Factus'},
        ),
        migrations.AlterModelOptions(
            name='homologacionmediopago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homologacionmunicipio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homologaciontributo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homologacionunidadmedida',
            options={},
        ),
        migrations.AlterModelOptions(
            name='metodopagofactus',
            options={'verbose_name': 'Método de Pago Factus', 'verbose_name_plural': 'Métodos de Pago Factus'},
        ),
        migrations.AlterModelOptions(
            name='municipiofactus',
            options={'verbose_name': 'Municipio Factus', 'verbose_name_plural': 'Municipios Factus'},
        ),
        migrations.AlterModelOptions(
            name='tributofactus',
            options={'verbose_name': 'Tributo Factus', 'verbose_name_plural': 'Tributos Factus'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedidafactus',
            options={'verbose_name': 'Unidad de Medida Factus', 'verbose_name_plural': 'Unidades de Medida Factus'},
        ),
        migrations.RenameIndex(
            model_name='documentoidentificacionfactus',
            new_name='fe_catalogo_factus__494214_idx',
            old_name='fe_catalogo__factus__36197f_idx',
        ),
        migrations.RenameIndex(
            model_name='documentoidentificacionfactus',
            new_name='fe_catalogo_codigo_228dfa_idx',
            old_name='fe_catalogo__codigo_d4afaf_idx',
        ),
        migrations.RenameIndex(
            model_name='metodopagofactus',
            new_name='fe_catalogo_factus__221599_idx',
            old_name='fe_catalogo__factus__11ac12_idx',
        ),
        migrations.RenameIndex(
            model_name='metodopagofactus',
            new_name='fe_catalogo_codigo_2f7919_idx',
            old_name='fe_catalogo__codigo_7db5b4_idx',
        ),
        migrations.RenameIndex(
            model_name='municipiofactus',
            new_name='fe_catalogo_factus__4e5e5a_idx',
            old_name='fe_catalogo__factus__ad799e_idx',
        ),
        migrations.RenameIndex(
            model_name='municipiofactus',
            new_name='fe_catalogo_codigo_2ccf2c_idx',
            old_name='fe_catalogo__codigo_72da58_idx',
        ),
        migrations.RenameIndex(
            model_name='tributofactus',
            new_name='fe_catalogo_factus__ef9060_idx',
            old_name='fe_catalogo__factus__f668f6_idx',
        ),
        migrations.RenameIndex(
            model_name='tributofactus',
            new_name='fe_catalogo_codigo_d25a31_idx',
            old_name='fe_catalogo__codigo_4048d2_idx',
        ),
        migrations.RenameIndex(
            model_name='unidadmedidafactus',
            new_name='fe_catalogo_factus__a236c0_idx',
            old_name='fe_catalogo__factus__fbd886_idx',
        ),
        migrations.RenameIndex(
            model_name='unidadmedidafactus',
            new_name='fe_catalogo_codigo_e6bbf4_idx',
            old_name='fe_catalogo__codigo_2bc059_idx',
        ),
    ]
